customers/urls.py
from django.urls import path

from customers import views
from customers import pdfviews,billviews
from customers import exportviews



app_name='customer_app'

urlpatterns=[
    path('create/',views.create,name='create'),
    # path('',views.CustomerPagination.as_view(),name="customer_pagination"),#it assists to show page
    path('list/',views.index,name='list'),#assists to show data
    path('edit/',views.edit,name='edit'),#here i pass primary key
    path('search/',views.search,name="search"),
    path('delete/',views.delete,name="delete"),
    path('customer-id-<int:cid>/order/',views.cus_ord_view,name="view"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('orders/bill/<int:cid>',billviews.GenerateBILL.as_view(),name="bill"),
    path('export/',exportviews.export,name="export"),
    
]

orders/urls.py
from django.urls import path
from orders import views,pdfviews

app_name = "order_app"

urlpatterns = [
    path('create/<int:cid>/', views.create, name = "create"),#I pass cid as for instance to show customer name when i click Add Order
    path('list/',views.index,name="list"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/customer-id-<int:cid>/order-id-<int:oid>/',views.edit,name="edit"),
    path('search/',views.search,name="search"),
    path('delete/<int:oid>/',views.delete,name="delete"),
    
]

rms/urls.py
from django.contrib import admin
from django.urls import path,include
# from registers.views  import dashboard

from registers import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView




urlpatterns = [
	path('admin/', admin.site.urls),
	path('',views.first_page,name="home"),
	path('dashboard/',views.dashboard,name="dashboard"),

#    path('',include('django.contrib.auth.urls')),
	
	path('user/',include('registers.urls', namespace = 'register_app')),
	path('customers/',include('customers.urls', namespace="customer_app")),
	path('products/',include('products.urls', namespace="product_app")),#namespace is the app_name in products.urls
	path('orders/',include('orders.urls', namespace="order_app")),
 
	
	
#    path('',include('registers.profile_urls',namespace="view_app")),

	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		 name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		 name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		 name="password_reset_confirm"),  
	   
	 #<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	 #<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		 name="password_reset_complete"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

# Create your models here.

from customers.models import Customer
from products.models import Product

class Order(models.Model):
    status=(
        ('Pending','Pending'),
        ('Delivered','Delivered'),
        ('Out for delivery','out for delivery')   
    )
    
    customer=models.ForeignKey(Customer,null=True,on_delete=models.SET_NULL)#customer_id is foreign key in tbl_orders
    '''this means if Customer is deleted then I want to set Order to NULL value in database but dont want to delete
        -if on_delete = models.CASCADE then deleting on Customer will also delete Order which is bad practice
    '''
    #Producat and Customer associated with Order
    product=models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)#maila order table Product ko dtails pauxu
    '''
    Similarly if Product is deleted then order set to Null value'''
    
    created_at=models.DateTimeField(max_length=50,null=True,auto_now=True)
    status=models.CharField(max_length=100,null=True,choices=status)
    quantity = models.IntegerField(default=1,blank=False)
    # total_price = models.DecimalField(max_digits=5,decimal_places=2,default=0)
    
    
    # def __str__(self):
    #     return self.product.name  #w/ relationship
    class Meta:
        db_table = 'tbl_orders'
    
    
    def save(self,*args,**kwargs):
    	super().save(*args,**kwargs)
   
    
    
    @property
    def get_total_item_price(self):#for particular product order total
        return self.quantity * self.product.price
    
    
    
      # def get_total_discount_item_price(self):
    #         return self.quantity * self.product.discount_price

    # def get_amount_saved(self):
    #     return self.get_total_item_price() - self.get_total_discount_item_price()

    # def get_final_price(self):
    #     if self.product.discount_price:
    #         return self.get_total_discount_item_price()
    #     return self.get_total_item_price()
    
  
    
    

orders/forms.py
from django import forms

from .models import Order,Product,Customer


# from products.models import Product
# from customers.models import Customer


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        
       
        exclude = ('total_price',)
       

orders/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse

from django.http import JsonResponse
from .models import Order,Customer,Product
from orders.forms import OrderForm
from orders.filters import OrderFilter
from django.forms import inlineformset_factory#It brings multiple form in group
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q

from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin


def create(request,cid):
    '''Below I replace OrderForm with'''
    
    OrderFormSet = inlineformset_factory(Customer,Order,fields='__all__',exclude=('total_price',),extra=5)  #access both customer and order form
    
    #it means maila customer lai click garda order ma bhako detail access garako xu with instance of customer
     #parent model and then child model---
    #we can have multiple order so we need to tell which to allow by fields
   
    cus = Customer.objects.get(pk=cid)
    formset = OrderFormSet(queryset=Order.objects.none(),instance=cus)#i pass instance because i am adding order of particular customer
    # print(formset)
    
    #queryset =Order.objects.none() la --> already bhako product inline form ma show hudaina maila Add order ma jada
    # form = OrderForm(initial={'customer':cus})#right customer is in model--comment this wh
    
    if request.method=='POST':
        # form = OrderForm(request.POST)
        formset = OrderFormSet(request.POST,instance = cus)
        if formset.is_valid():
            formset.save()
        messages.success(request,"Order is successfully added",extra_tags = 'alert')
        return redirect('customer_app:view', cid)
    
    return render(request,'orders/create.html',{'formset':formset,'customer':cus})





@login_required(login_url='/user/login/')
def index(request):
    orders=Order.objects.all().order_by("-id")
    total_orders=orders.count()
    # myFilter = OrderFilter(request.GET,queryset=orders)
    # orders = myFilter.qs
    # # customers=Customer.objects.all()
    pending=orders.filter(status='Pending').count()#filter la choose(search)  garxa and all pending lai count garxa
    delivered=orders.filter(status="Delivered").count()
    
    
    # -----------------Call for pagination logic----------------------------
    orders = pagination(request,orders)#return pagination orders data
         
    context={
        'orders':orders,'total_orders':total_orders,
        'orders_pending':pending,'orders_delivered':delivered,
        # 'myFilter':myFilter,
        'start':orders.start_index(),
        'end':orders.end_index()
        
        }
    return render(request,'orders/index.html',context)


        
    


def pagination(request,object):
    page = request.GET.get('page', 1)#means page  number 1
    paginator = Paginator(object, 5)
  
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        #if page is out of range show last page
        orders = paginator.page(paginator.num_pages)
        
    return orders

    
def search(request):
    data = dict()
    field_value = request.GET.get('query')
    print(field_value)
    
    # products = Product.objects.all()
    # myFilter = ProductFilter(request.GET,queryset=products)
    # products = myFilter.qs
  
  
    if field_value:
        orders = Order.objects.filter(
                                            Q(product__name__contains=field_value)
                                           |Q(status__icontains=field_value) 
                                        
                                           | Q(quantity__contains=field_value)
                                            | Q(customer__name__contains=field_value)
                                           )
        context = {'orders': orders}
            
        data['html_list'] = render_to_string('orders/get_search_orders.html',context,request=request)
        return JsonResponse(data)
    

    else:
        orders = Order.objects.all()
       
        context = {'orders': orders}
        data['html_list'] = render_to_string('orders/get_search_orders.html',context,request=request)

        return JsonResponse(data)


def edit(request, cid, oid):    
    # ord=Order.objects.get(pk=oid) #i get all value and show that value to next page
    
    ord = get_object_or_404(Order,pk = oid)
    customer = get_object_or_404(Customer,pk=cid)
    
    form=OrderForm(instance=ord)
    
    # cus = get_object_or_404(Customer,pk = cid)
   
    
    if(request.method=='POST'):
        
        form=OrderForm(request.POST,instance=ord)
        if(form.is_valid()):
            form.save()
            messages.success(request,'Order is successfully updates.',extra_tags='alert')
            
            return redirect('customer_app:view', cid)
            
            # return redirect("/customers/order/", pk = cid)#maila update.html ko save garda or post ma jada yo url ma redirect hunxa

    # else:
    #     form = ProductForm()
        
  
    return render(request,'orders/update.html',{'form':form,'customer_record':customer})


def delete(request, oid):
        # cus=Customer.objects.get(id=pk)
    ord = get_object_or_404(Order,pk = oid) 
    
    if request.method=='POST':#if i confirm in delete.html page
        ord.delete()   #grab customer details and delete and after deleting moves to /customers/list/
        return redirect('order_app:list')
    
    return render(request,'orders/delete.html',{'orders':ord})#urls.py ko url render ma url search garxa at first

orders/templates/orders/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit customers{% endblock%}

{% block content %}
<main>
   
  
    <div class="container">
    
        <div class="row justify-content-center">
            
            <div class="col-lg-9">
                <div class="card shadow-lg border-0 rounded-lg mt-5 " >
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-2">
                        
                                <a href="/" class="btn btn-sm btn-primary">   <i class="fas fa-home"></i> HOME</a>
                            </div>
                            <div class="col-md-8">
                                <h2 class="text-center  my-4">Add Order For <strong>{{customer.name}}</strong> </h2></div>
                            </div>
                        </div>
     
             
                    
                    <div class="card-body">
                        
                      
                        <form method="POST" action="" style="display: inline;">
                            {% csrf_token %}
                            {{formset.management_form}}
                            {% for form in formset %}
                            <!--line  by line lauxa-->
                            {{form}}
                            <hr>
            
                            {% endfor %}
            
            
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="{% url 'customer_app:list' %}" class="btn btn-sm btn-block btn-danger">Back</a>
                                </div>
                                <div class="col-md-6">
                                      
                            <button type="submit" class="btn btn-sm btn-block btn-success">Save</button>
                            <!--save huda post method hunxa and create views ko redirect ma janxa-->
            
                                    
                                </div>
                            </div>
                         
                        </form>
                        
                    </div>
                 
                  
                </div>
            </div>
        </div>
    </div>
</main>
<!-- </body> -->
<style>
    body{
		background: #a1c4fd;
	
	  }
</style>

{% endblock%}

orders/templates/orders/delete.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="card border-dark col-md-12">
    
    <h3 class="card-header bg-secondary" style="color:white;">Are you sure want to delete <strong>{{orders.product.name}}</strong> details ?</h3>
    
    <div class="card-body">
        <form  method="POST">
           
            <a href="{% url 'order_app:list'%}" class="btn btn-outline-danger">Cancel</a>
        
            {% csrf_token %}
        
            <button type="submit" class="btn btn-success" 
            onclick="document.getElementById('id01').style.display='block'">
            Confirm</button>
          
        </form>
    </div>
</div>

<style>
    body{
		background: #a1c4fd;
	
	  }
</style>

{% endblock %}

orders/templates/orders/get_search_orders.html
{% for order in orders %}
            
<tr style="text-align: center;">   
    <td>{{order.id}}</td>
    <td>{{order.customer.id}}</td>
   
   
 
    <td>{{order.product.name}}</th>
        <!-- <td>{{order.product.category}}</td> -->
        <td>{{order.quantity}}</td>

    <td>{{order.created_at}}</td>
    <td>{{order.status}}</td>
   
    <td><a href="{% url 'order_app:edit' order.customer.id order.id%}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
        <a href="{% url 'order_app:delete' order.id%}" class="btn btn-danger btn-sm"><i class="fa fa-trash-alt"></i></a>
    </td>
</tr>

{% empty %}
<tr>
   <td  colspan="7" class="text-center alert alert-danger">No Orders Found</td>
</tr>

{% endfor %}

orders/templates/orders/index.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Orders{% endblock %}

{% block javascript %}
<script src="{% static 'vendor/js/scripts.js' %}"></script>
<script src="{% static 'products/search.js' %}"></script>

{% endblock %}

{% block content %}

<!--Nav bar and side bar which include search and others-->

<!--------------For navbar and toggle bar----------------------------->
{% include 'navbar.html' %}


<!---------------For total order and total proce card---------------------------->
{% include 'includes/card.html' %}


<!--for django messages-->
{% include 'message.html' %}


<!--Search bar and invoice-->
<div class="col">
    <div class="card border-dark" style="margin-left:18%;padding-right:15%;padding:10px;margin-bottom:10px;">
        <h3 class="card-header"> Orders Of All Customers</h3>

    </div>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-left:20%;">

    {% include 'includes/formsearch.html' %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="{% url 'order_app:pdf' %}" class="btn  btn-danger ml-2 mt-1"> <i class="fas fa-file-pdf"></i>
                    PDF</a>
            </li>

        </ul>

    </div>
</nav>

<hr>



<!------------------List of Order in table------------------------->
{% include 'includes/order_list.html' %}
<!----------------------------------------------------------------->


<!--Below code is for pagination -->

<div class="row">

    <div class="col">

        <div class="mb-4" style="margin-left:22%;position:fixed;">
            <Strong> Showing {{start}} to {{end}} of {{total_orders}} orders</Strong>
        </div>

    </div>

    <div class="col">


        <div style="margin-right:40%;" class="float-right">

            {% if orders.has_other_pages %}
            <ul class="pagination">
                {% if orders.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ orders.previous_page_number }}">Previous</a>
                {% else %}

                {% endif %}

                {% for i in orders.paginator.page_range %}
                {% if orders.number == i %}
                <!--recent page ma dark dekhauxa-->
                <li class="btn btn-info mb-4"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}

                <li><a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}

                {% if products.has_next %}

                <a class="btn btn-outline-info mb-4" href="?page={{ orders.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ orders.paginator.num_pages }}">Last</a>
                {% else %}
                <!-- <li class="btn btn-outline-info mb-4"><span>&raquo;</span></li> -->
                {% endif %}
                <hr>
            </ul>
            {% endif %}
        </div>
    </div>
</div>




{% endblock%}

orders/templates/orders/pdf.html
{% extends 'base.html' %}
{% block title%}Customer Details{% endblock %}
{% block content %}
      
        <style type="text/css">
            body {
                
                font-size: 13px;
            
            }
            .header {
                font-size: 25px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }

            tr:first-child{
                outline: thin solid transparent;
                height: 40px;
              }
           
        </style>
        

         
            

       
        <div class='wrapper'>
            <div class='header'>
                
                <p class='title'>Orders Invoice </p>
            </div>
            <div class='details'>
              Date : {{myDate}}
                <hr class='hrItem' />
            </div>
        </div>
        <br>

        <div class="container">
            <div class="col-md-12">
        
                <table class="table" border="1">
                    <thead class="thead-dark">
                        <tr>
                            <th>Order Id</th>
                            <th>Cus.Id</th>
                            <th>Category</th>
                            <th>Product</th>
            
                            <th>Quantity</th>
                          
                            <th>Status</th>
                            <!-- <th>Quantity</th> -->
                         
                          
                        </tr>
                       
            
                    </thead>
                    <tbody>
                        
                        {% for order in orders %}
                        
                        <tr style="text-align: center;">    
                            <td>{{order.id}}</td>
                            <td>{{order.customer.id}}</td>
                            <td>{{order.product.category}}</td>
                           
                         
                            <td>{{order.product.name}}</th>
                                <td>{{order.quantity}}</td>
            
        
            
                            
                            <td>{{order.status}}</td>
                           
                         
                        </tr>
            
                        {% endfor %}
                    </tbody>
                </table>
        
    </div>
</div> 

{% endblock %}

orders/templates/orders/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit customers{% endblock%}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5 " >
                    <div class="card-header"><h2 class="text-center font-weight-light my-4">Edit Order</h2></div>
                    
                    <div class="card-body">
                      
                        <form method="POST" class="justify-content-center" >
                          {% csrf_token %}

                          {{form|crispy}}

                           
                          <a href="{% url 'customer_app:view' customer_record.id %}" class="btn btn-success">Back</a>
                          <button type="submit" class="btn btn-danger">Save</button>
                          
                        </form>
                        
                    </div>
                 
                  
                </div>
            </div>
        </div>
    </div>
</main>
<!-- </body> -->
<style>
    body{
		background: #a1c4fd;
	
	  }
</style>

{% endblock%}